# ------------ Additional parameters: checkboxes ---------------
checkboxes:
  # Do you have a valid driver's license? (yes/no checkbox)
  Driver: "yes"
  # Will you now, or in the future, require sponsorship for employment visa status (e.g. H-1B visa status)? (yes/no checkbox)
  # This is relative to the location and your citizenship applying above, and same with legallyAuthorized.
  Sponsor: "no"
  # Are you legally authorized to work in COUNTRY? (yes/no checkbox)
  Legally authorized: "yes"
  # We must fill this position urgently. Can you start immediately? (yes/no checkbox)
  Urgent: "yes"
  # Are you comfortable commuting to this job's location? (yes/no checkbox)
  Commuting: "yes"
  # Have you completed the following level of education: DEGREE TYPE? (yes/no checkbox)
  High School Diploma: "yes"
  Bachelor's Degree: "yes"
  Associate's Degree: "no"
  Master's Degree: "yes"
  Master of Business Administration: "no"
  Doctor of Philosophy: "no"
  Doctor of Medicine: "no"
  Doctor of Law: "no"
  # Are you willing to undergo a background check, in accordance with local law/regulations?
  Background Check: "yes"
  # Are you comfortable working in a remote setting?
  Remote: "yes"
  # Are you willing to relocate?
  Relocate: "no"
  # Are you a US Citizen?
  US Citizen: "yes"
  # Are you willing to travel 25% of the time?
  Travel 25%: "yes"
  # Are you willing to take a drug test, in accordance with local law/regulations?
  Drug Test: "yes"
  # Are you comfortable working in a hybrid setting?
  Hybrid: "no"
  # Are you comfortable working in an onsite setting?
  Onsite: "no"
  # Questions related with North korea
  North Korea: "no"
  # Data retention policy
  Data retention: "no"
  # At this time, we are only considering candidates in the US and Canada for this role. Are you physically located in the United States or Canada? Required
  United States: "yes"
  # Are you authorized to work in the U.S. or Canada? Required
  Authorized: "yes"
  # Will you now or in the future require sponsorship for employment visa status? Required
  Visa: "no"
  # Have you earned a Bachelor’s level degree or higher in the Computer Science or Software Engineering field? Required
  Bachelor: "yes"
  # Do you have at least 5 years of direct professional work experience as a Software Engineer? Required
  Experience: "yes"
  # In the past two years, have you signed an employment agreement that contains a non-competition restriction?
  Competition: "no"
  # Are you 18 years or older? 
  Older: "yes"
  # Are you comfortable working in a remote setting?
  Remote: Yes
  # Are you willing to undergo a background check, in accordance with local law/regulations?
  Background: Yes
  # Do you have experience evaluating client security controls, architecture and operations?
  Experience: Yes
  # Do you have experience triaging Windows and Linux hosts, with Network Traffic Analysis and with Log Data Analysis?
  Windows: Yes
  # Do you have at least 5 years of incident response, security operations or strategic security consulting experience?
  Incident: Yes
  #Have you ever worked for Able To before?

  # Gender (Male - 0 / Female - 1 / Decline to Answer - 2)
  Gender: "Decline to Answer"
  #  Veteran status  ( I identify as one or more listed above - 0 /  I am not a protected veteran - 1 /  I don't wish to answer - 2  ))
  Veteran: "I don't wish to answer "
  #  Disability status  ( Yes, I Have A Disability - 0 /  No, I Don't Have A Disability - 1 /  I don't wish to answer - 2  ))
  Disability: "I don't wish to answer "
  # Race/Ethnicity  (Hispanic or Latino - 0 /  American Indian or Alaska Native (Not Hispanic or Latino) - 1 / Asian (Not Hispanic or Latino) - 2 /  Black or African American (Not Hispanic or Latino)  - 4 /  Native Hawaiian or Other Pacific Islander (Not Hispanic or Latino) - 5 /  Two or More Races (Not Hispanic or Latino) - 6 /  White (Not Hispanic or Latino - 7 /  I prefer not to specify - 8  )
  Race: "I prefer not to specify"
  # When is your availability to start? 
  Availability: immediate
  Years: "yes"
  Citizen: "Yes"

  # Add a custom question keyword and answer "yes" - yes , "no" - no based on /data/additionalQuestions.txt file so that once the bot reruns it will fill the answer from here.
  # For example question is: Do you want to live in Spain? You should write Spain:"yes" for yes or Spain:"no" for no radio button click. you can also write spain the text is case insensitive.
  # Have ired
