personalInfo:
  First Name: 
  Last Name: 
  Phone Country Code: +1 # See linkedin for your country code, must be exact
  Mobile Phone Number: 
  Street address: Remote
  City:  # Include the state/province as well!
  State: 
  Zip: 
  Linkedin: 
  Website:  # github/website is interchangable here

# How many years of "TECHNOLOGY" experience do you currently have? (whole numbers only)
experience do you currently have:
  Accounting/Auditing: 0
  Administrative: 0
  Advertising: 0
  Analyst: 6
  Art/Creative: 0
  Business Development: 1
  Consulting: 0
  Customer Service: 0
  Distribution Design: 0
  Education: 0
  Engineering: 6
  Finance: 0
  General Business: 2
  Health Care Provider: 0
  Human Resources: 0
  Information Technology: 8
  Legal: 0
  Management: 1
  Manufacturing: 0
  Marketing: 0
  Public Relations: 0
  Purchasing: 0
  Product Management: 2
  Project Management: 3
  Production: 0
  Quality Assurance: 0
  Research: 0
  Sales: 0
  Science: 0
  Strategy/Planning: 0
  Supply Chain: 0
  Training: 0
  Writing/Editing: 0
  # default to put for any skill that you did not list
  default: 2
  # end normal ones, put your custom ones here
  C++: 2
  Python: 5
  Javascript: 3
  # Node: 3
  # -- end of experience do you currently have, bot added ones below

# Questions having these technology keywords inside (whole numbers only) - case insensitive
python: 3
Spring Boot: 0
java: 3
PHP: 0
Laravel: 0
SASS: 3
React: 3
React Native: 2
Django: 0
SAP: 2
Splunk: 8
IR: 8
incident response: 8
automation: 5
pentest: 5
penetration: 6
security: 6
ipt: 0
MySQL: 4
Shopify: 0
Typescript: 3
JavaScript: 3
Angular: 0
Redux.js: 2
Angular Command Line Interface (CLI): 0
selenium: 3
C++: 2
C#: 2
C (Programming Language): 2
Software Development: 3
Linux: 10
Cross-functional team: 0
Social media platforms: 0
Microsoft Azure: 10
AWS: 10
.NET: 0
Docker: 6
k8s: 4
kubernetes: 4
cloud: 8
SQL: 6
experience: 8
# add custom one here

universityGpa: 4.0

# What is your level of proficiency in a: polski? Required
level of proficiency:
  english: Native or bilingual # None, Conversational, Professional, Native or bilingual

# Other queations, you can add custom ones below and bot will also add the unrecognized ones at the end
# Can you provide a ballpark salary range you'd be looking for? Required / # Desired salary Required / Salary expectations for
Salary: 180000
# If you selected Word of mouth, Referral or Other from the question above, please specify in the box below.
Word of mouth, Referral or Other: None
# College or University
College or University: 
# Have you ever applied at ... before? Required
Have you ever applied: No
#  Please provide 3 references with their name, phone number, and email address. Required
#References: A, 045,abc@gmail.com | B,234,abc@gmail.com | C,2134,abc@gmail.com
#  How many hours are you available every week? Required
Hours are you available every week: 40
#  What is your desired hourly pay rate (in USD)? Required
Hourly pay rate: 80
#  Notice period in weeks Required
Notice period: 2 weeks
#Your message to the hiring manager
Hiring Manager: See Resume
#  Please evaluate on a scale from 1 to 10 you ability to manage technical issues on different social media platforms? Required
#Manage Technical Issues: 8

